# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DevFest Veneto 2018"
email: "veneziagdg@gmail.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/devfest-veneto-18"
url: "https://gdg-venezia.github.io"
permalink: "/blog/:title"
# Update
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, venezia"
twitterAccount: ""
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/forms/BRl1SPguBqhNAOTG2"
c4sponsorsUrl: "https://docs.google.com/document/d/1H5YvAYf1elYBcqlgPs2LH1-93z22hG0Y8j7cG_6Z_DU/edit?usp=sharing"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/#location", text: "Location"}
 - {permalink: "/#partners", text: "Partners"}
 - {permalink: "/#team", text: "Team"}
 - {permalink: "/#tickets", text: "Biglietti"}
bottomNavigationLinks:
 - {link: "https://goo.gl/forms/BRl1SPguBqhNAOTG2", text: "Diventa uno speaker"}
rightNavigationButtons:
 - {link: "https://goo.gl/forms/BRl1SPguBqhNAOTG2", text: "Diventa uno speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "DevFest Veneto 2018"
eventDate: "24 Novembre 2018"
heroButtons:
 - {permalink: "/#tickets", text: "Biglietti"}
 - {link: "https://goo.gl/forms/BRl1SPguBqhNAOTG2", text: "Diventa uno speaker"}
 - {link: "https://docs.google.com/document/d/1H5YvAYf1elYBcqlgPs2LH1-93z22hG0Y8j7cG_6Z_DU/edit?usp=sharing", text: "Diventa un partner"}

# About Block
aboutTitle: "Che cos'è una DevFest?"
aboutBlock:
 - {title: "Talk", image: "conference.jpg", text: "" }
 - {title: "Codelab", image: "workshop.jpg", text: "" }
 - {title: "Networking", image: "hackathon.jpg", text: "" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1", specialCharacter: "", info: "giornata", detail: ""}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: ""}
 - {count: "150", specialCharacter: "", info: "partecipanti", detail: ""}

# Latest News Block
latestNewsTitle: "Ultime notizie"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speaker"
rockstarSpeakersButtonText: "Tutti gli speaker"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Fabrica"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Via Postioma, 54/F" 
eventAddressLocality: "Catena di Villorba TV"
eventPostalCode: "31020"
eventStartTime: "2018-11-24T09:30"
eventDoorTime: "09:30"
eventEndTime: "2018-11-24T18:30"
eventPlaceCoordinates: "45.740209, 12.266216"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Diventa un partner"

# Footer
socialLinks:
 - {link: "https://twitter.com/gdgvenezia", icon: "twitter"}
 - {link: "https://www.facebook.com/gdgvenezia", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.facebook.com/gdgvenezia", text: "Facebook"}
   - {link: "https://twitter.com/gdgvenezia", text: "Twitter"}
   - {link: "https://www.meetup.com/it-IT/GDG-Venezia/", text: "Meetup"}

# Blog
blogTitle: "Ultime notizie"

# Speakers List Block
showSessions: true