# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DevFest Veneto 2018"
email: "veneziagdg@gmail.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/devfest-veneto-18"
url: "https://gdg-venezia.github.io"
permalink: "/blog/:title"
# Update
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Venezia"
organizerAlternateName: "Google Developer Group Venezia"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/#location", text: "Location"}
 - {permalink: "/#partners", text: "Partners"}
 - {permalink: "/#team", text: "Team"}
 - {permalink: "/#tickets", text: "Biglietti"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Diventa uno speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Diventa uno speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "DevFest Veneto 2018"
eventDate: "24 Novembre 2018"
heroButtons:
 - {permalink: "/#tickets", text: "Biglietti"}
 - {link: "https://bit.ly/dfua-c4p", text: "Diventa uno speaker"}
 - {link: "https://bit.ly/dfua-c4p", text: "Diventa un partner"}

# About Block
aboutTitle: "Che cos'è una DevFest?"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Ultime notizie"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speaker"
rockstarSpeakersButtonText: "Tutti gli speaker"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Fabrica"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Via Postioma, 54/F" 
eventAddressLocality: "Catena di Villorba TV"
eventPostalCode: "31020"
eventStartTime: "2018-11-24T09:30"
eventDoorTime: "09:30"
eventEndTime: "2018-11-24T18:30"
eventPlaceCoordinates: "45.740209, 12.266216"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Footer
socialLinks:
 - {link: "https://twitter.com/gdgvenezia", icon: "twitter"}
 - {link: "https://www.facebook.com/gdgvenezia", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.facebook.com/gdgvenezia", text: "Facebook"}
   - {link: "https://twitter.com/gdgvenezia", text: "Twitter"}
   - {link: "https://www.meetup.com/it-IT/GDG-Venezia/", text: "Meetup"}

# Blog
blogTitle: "Ultime notizie"

# Speakers List Block
showSessions: true